In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [9]:
#make ones array with data type intger
x= np.ones(3,dtype= int)
x

array([1, 1, 1])

## Q#2: Create y array with elements equal to 0.

In [12]:
#make zeros array with data type intger
y=np.zeros(3,dtype=int)
y

array([0, 0, 0])

## Q#3: Add x and y arrays.

In [13]:
x+y


array([1, 1, 1])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [17]:
print('dimension :',x.ndim)
print('shape',x.shape)
print('size',x.size)
print('type',x.dtype)

dimension : 1
shape (3,)
size 3
type int32


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [46]:
w=np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [47]:
z=np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [48]:

#first need to Reshape z to be a 2D array 
z_resh= z.reshape(-1, 1)
#  hstack 2D array
newArray = np.hstack((z_resh, w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [49]:
for i in range(len(newArray)): # i = colum
    for j in range(len(newArray[i])):#j = row
        print(newArray[i][j])

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [53]:
newArray=newArray[::-1]
newArray

array([[ 3, 15, 16],
       [ 2, 13, 14],
       [ 1, 11, 12]])

## Q#10: Decrement all elements of "newArray" with 1.

In [54]:
newArray -=1
newArray

array([[ 2, 14, 15],
       [ 1, 12, 13],
       [ 0, 10, 11]])

## Q#11: Find smallest and biggest values in "newArray".

In [55]:
smallest = np.min(newArray)
biggest = np.max(newArray)
print('smallest value is ',smallest)
print ('biggest value is ',biggest)

smallest value is  0
biggest value is  15


## Q#12: Print the first row of "newArray" using indexing.

In [56]:
newArray[0]

array([ 2, 14, 15])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [57]:
newArray[1][1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [68]:
zero=newArray[2][0]
thirteens=newArray[1][2]
#print 
print('number in index[0][0] =',zero)
print ('number in index[1][2] =',thirteens)

number in index[0][0] = 0
number in index[1][2] = 13


## Q#15: Change the shape of "newArray" to (9,1).

In [74]:
newArray=newArray.reshape(9,1)
newArray

array([[ 2],
       [14],
       [15],
       [ 1],
       [12],
       [13],
       [ 0],
       [10],
       [11]])

## Q#16: Change the shape of "newArray" to (3,2).

In [75]:
newArray

array([[ 2],
       [14],
       [15],
       [ 1],
       [12],
       [13],
       [ 0],
       [10],
       [11]])

In [76]:
#make 2D arary using 9*1 array  
newArray=newArray[:6].reshape(3, 2) 
newArray

array([[ 2, 14],
       [15,  1],
       [12, 13]])

# Well Done 🎉